# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-17 11:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promo',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='js_promo_promo', serialize=False, to='cms.CMSPlugin')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('sub_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='sub title')),
                ('summary', models.TextField(blank=True, default='', verbose_name='summary')),
                ('link_text', models.CharField(blank=True, max_length=255, null=True, verbose_name='link text')),
                ('link_url', models.CharField(blank=True, max_length=255, null=True, verbose_name='link url')),
                ('image', filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promo_image', to=settings.FILER_IMAGE_MODEL, verbose_name='image')),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),
    ]
